### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by paulelms** [davydovanton/rubyunderhood#1]
> Иногда, конечно. Но общение самое важная и интересная часть идеи @**jsunderhood**.
> 
> но в твиттере и конечно **же новыми** функциями
> 
> постарайтесь сделать всё вышеописанное в течение **пары пяти** минут

**Comment by davydovanton** [comment]
Павел, спасибо! :+1: 
А можешь ПР сделать? Если нет - я сам поправлю.
